# Generated by Django 4.2.23 on 2025-08-26 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('number_of_seats__gte', 1), ('number_of_seats__lte', 10)), name='seats_between_1_and_10'),
        ),
        migrations.AddConstraint(
            model_name='traveloption',
            constraint=models.CheckConstraint(check=models.Q(('available_seats__lte', models.F('total_seats'))), name='available_seats_lte_total_seats'),
        ),
    ]
